### ISSUE TITLE
'NoneType' object has no attribute 'delete'

### ISSUE THREAD

**Issue by DahaWong** [DahaWong/castpod#17]
Traceback (most recent call last):
  File "/home/daha/project/castpod/castpod/callbacks/message.py", line 71, in save_subscription
    podcast = Podcast.validate_feed(feed['url'])
  File "/home/daha/project/castpod/castpod/models.py", line 170, in validate_feed
    return podcast or cls(feed=feed).save()
  File "/home/daha/download/pypy3.7-v7.3.2-linux64/site-packages/mongoengine/document.py", line 378, in save
    self.validate(clean=clean)
  File "/home/daha/download/pypy3.7-v7.3.2-linux64/site-packages/mongoengine/base/document.py", line 433, in validate
    raise ValidationError(message, errors=errors)
mongoengine.errors.ValidationError: ValidationError (Podcast:None) (Invalid scheme  http in URL:  http://pan.icu/feed: ['feed'])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/daha/download/pypy3.7-v7.3.2-linux64/site-packages/telegram/utils/promise.py", line 77, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/daha/project/castpod/castpod/callbacks/message.py", line 118, in save_subscription
    raise e
  File "/home/daha/project/castpod/castpod/callbacks/message.py", line 75, in save_subscription
    podcast.delete()
AttributeError: 'NoneType' object has no attribute 'delete'

**Comment by DahaWong** [comment]
原因：URL 的 Validation 认证。
